version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_MODELS=/models  # Apenas se quiser volume para persistir
    volumes:
      - ollama_models:/models
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 3 && ollama pull cogito && wait"]

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"  # Alterei a porta local para evitar conflito
    volumes:
      - mongo_data:/data/db

  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - ollama
      - mongo

volumes:
  ollama_models:
  mongo_data:
